### ISSUE TITLE
mtp

### ISSUE THREAD

**Issue by Grace5921** [ShadowLeaf1/android_device_samsung_grandneove3g#5]
mtp is not working because 

`BOARD_UMS_LUNFILE                 := "/sys/class/android_usb/android0/f_mass_storage/lun/file"`
`TARGET_USE_CUSTOM_LUN_FILE_PATH   := "/sys/devices/platform/dwc_otg.0/gadget/lun0/file"`

in most of cases this is wrong go and check for that folder ad file

**Comment by ShadowLeaf1** [comment]
And can you please give me your whatsapp no?

**Comment by Grace5921** [comment]
sorry i don't have whatsapp because my device is always in recovery to test new cm builds

**Comment by ShadowLeaf1** [comment]
Can u tell me that how can i fix that?

**Comment by ShadowLeaf1** [comment]
Do i have to comment those lines?

**Comment by Grace5921** [comment]
use any file manager and check for this file /sys/class/android_usb/android0/f_mass_storage/lun/file and /sys/devices/platform/dwc_otg.0/gadget/lun0/file  i am sure it's not there

**Comment by ShadowLeaf1** [comment]
If that will be not there , I can comment those lines and build.Right?

**Comment by Grace5921** [comment]
yes you need to find that file and fix path of that file so mtp should work

**Comment by ShadowLeaf1** [comment]
ok. Thanks by the way.

**Comment by Grace5921** [comment]
welcome

**Comment by ShadowLeaf1** [comment]
BOARD_UMS_LUNFILE := "/sys/class/android_usb/android0/f_mass_storage/lun/file" It's there

But TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/dwc_otg.0/gadget/lun0/file" It's not there.



![81d8b6f9-aa68-449a-9d17-40c4eb23fe0d](https://cloud.githubusercontent.com/assets/17350338/14782273/ea8f5402-0b05-11e6-8f10-ff896281469a.jpg)
![81d8b6f9-aa68-449a-9d17-40c4eb23fe0d](https://cloud.githubusercontent.com/assets/17350338/14782276/eda986f8-0b05-11e6-832d-0040a5c16d9a.jpg)

**Comment by Grace5921** [comment]
search for thos lun and  lun0 if you find this files then replace those lines with new path and mtp should work after that

**Comment by ShadowLeaf1** [comment]
unfortunately there are no lun and lun0 .

**Comment by Grace5921** [comment]
then it's only way to fix mtp there is but you can't find because it's hard
